version: '3.8'

services:
  node-app:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: localhost
      DB_PORT: 27017
      DB_USERNAME:
      DB_PASSWORD:
      DB_NAME:
    # ports:
      # - 3000:3000