version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: test
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data # Volumen | Nombre del volumen

  node-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    environment:
      DB_HOST: db # Sin Docker seria 'localhost'
      DB_PORT: 5432
      DB_USERNAME:
      DB_PASSWORD:
      DB_NAME:
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/app #Bind amount | Sintaxis de ruta
      - /usr/app/node_modules # Sintaxis para ignorar una ruta

volumes:
  db_data: