version: '3.8'

services:
  db:
    image: mongo
    container_name: db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db # Volumen | Nombre del volumen

  node-app:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    environment:
      # MONGO_URI: mongodb://localhost:27017/test
      MONGO_URI: mongodb://db:27017/test
      DB_HOST: db # Sin Docker seria 'localhost'
      DB_PORT: 27017
      DB_USERNAME:
      DB_PASSWORD:
      DB_NAME:
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/app #Bind amount | Sintaxis de ruta
      - /usr/app/node_modules # Sintaxis para ignorar una ruta

volumes:
  db_data: